/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ass
 */
public class GUI extends javax.swing.JFrame {
	BrainFuckInterpreter bfi;
    /**
     * Creates new form GUI
     */
    public GUI(BrainFuckInterpreter b) {
    	this.bfi = b;
    	/*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        errorDialogBox = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        errorText = new javax.swing.JLabel();
        errorOkayButton = new javax.swing.JButton();
        aboutDialogBox = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        aboutOkayButton = new javax.swing.JButton();
        helpDialogBox = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        inputPane = new javax.swing.JOptionPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        inputArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        debugArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        infoPane = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        filePathTextBox = new javax.swing.JTextField();
        filePathButton = new javax.swing.JRadioButton();
        sourceTabButton = new javax.swing.JRadioButton();
        startButton = new javax.swing.JButton();
        clearSourceButton = new javax.swing.JButton();
        clearOutputButton = new javax.swing.JButton();
        clearDebugButton = new javax.swing.JButton();
        clearAllButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        menuOpen = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuSaveAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        menuCut = new javax.swing.JMenuItem();
        menuCopy = new javax.swing.JMenuItem();
        menuPaste = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenuItem();
        menuSampleProgram = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuHelp = new javax.swing.JMenuItem();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        errorDialogBox.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        errorDialogBox.setTitle("ERROR!");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Error:");

        errorText.setText("Error Text");

        errorOkayButton.setText("Okay");
        errorOkayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorOkayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout errorDialogBoxLayout = new javax.swing.GroupLayout(errorDialogBox.getContentPane());
        errorDialogBox.getContentPane().setLayout(errorDialogBoxLayout);
        errorDialogBoxLayout.setHorizontalGroup(
            errorDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialogBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(errorDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(errorDialogBoxLayout.createSequentialGroup()
                        .addGroup(errorDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(errorDialogBoxLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(errorText))
                            .addComponent(jLabel2))
                        .addGap(0, 184, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, errorDialogBoxLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(errorOkayButton)))
                .addContainerGap())
        );
        errorDialogBoxLayout.setVerticalGroup(
            errorDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialogBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(errorOkayButton)
                .addContainerGap())
        );

        aboutDialogBox.setTitle("About - JavaFuck");

        jLabel3.setText("About");
        jLabel3.setToolTipText("");

        jTextPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextPane1.setEditable(false);
        jTextPane1.setText("JavaFuck is an interpreter for the esoteric programming language 'Brainfuck'. This inerpreter is written in java, and therefore is extremely portable. It is a work in progress, and is working it's way toward becoming a full IDE for the Brainfuck language. For more information on the language, choose \"Help\" from the Help dropdown menu.");
        jScrollPane6.setViewportView(jTextPane1);

        aboutOkayButton.setText("Okay");
        aboutOkayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutOkayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aboutDialogBoxLayout = new javax.swing.GroupLayout(aboutDialogBox.getContentPane());
        aboutDialogBox.getContentPane().setLayout(aboutDialogBoxLayout);
        aboutDialogBoxLayout.setHorizontalGroup(
            aboutDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutDialogBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aboutDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutDialogBoxLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(aboutDialogBoxLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutDialogBoxLayout.createSequentialGroup()
                        .addGap(0, 269, Short.MAX_VALUE)
                        .addComponent(aboutOkayButton)))
                .addContainerGap())
        );
        aboutDialogBoxLayout.setVerticalGroup(
            aboutDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutDialogBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboutOkayButton)
                .addContainerGap())
        );

        helpDialogBox.setTitle("Brainfuck Help");

        jLabel4.setText("Help");

        jPanel1.setToolTipText("");

        jLabel5.setText("Brainfuck Tutorial - Coming Soon!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(555, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(444, Short.MAX_VALUE))
        );

        jScrollPane7.setViewportView(jPanel1);

        javax.swing.GroupLayout helpDialogBoxLayout = new javax.swing.GroupLayout(helpDialogBox.getContentPane());
        helpDialogBox.getContentPane().setLayout(helpDialogBoxLayout);
        helpDialogBoxLayout.setHorizontalGroup(
            helpDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpDialogBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(helpDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                    .addGroup(helpDialogBoxLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        helpDialogBoxLayout.setVerticalGroup(
            helpDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpDialogBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7)
                .addContainerGap())
        );

        inputPane.setInputValue('A');
        inputPane.setMessage("Enter input here: ");
        inputPane.setToolTipText("");
        inputPane.setWantsInput(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaFuck - Java Brainfuck Interpreter");
        setBackground(new java.awt.Color(0, 0, 0));

        inputArea.setColumns(20);
        inputArea.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        inputArea.setRows(5);
        inputArea.setText("This is a sample hello world program\n\n+++++ +++++        Set pointer 0 to 10\n[\n > +++++ ++        Set pointer 1 to 70\n > +++++ +++++     Set pointer 2 to 100\n > +++++ +++++ ++  Set pointer 3 to 120\n > +++             Set pointer 4 to 30\n\n <<<< -            Decrement pointer 0\n]\n\n> ++.                   Output 'H'  Pointer 1 = 72\n> +.                    Output 'e'  Pointer 2 = 101\n+++++ ++.               Output 'l'  Pointer 2 = 108\n.                       Output 'l'  Pointer 2 = 108\n+++.                    Output 'o'  Pointer 2 = 111\n>> ++.                  Output ' '  Pointer 4 = 32\n<<< +++ +++++ +++++ ++. Output 'W'  Pointer 1 = 87\n>.                      Output 'o'  Pointer 2 = 111\n+++.                    Output 'r'  Pointer 2 = 114\n----- -.                Output 'l'  Pointer 2 = 108\n----- ---.              Output 'd'  Pointer 2 = 100\n>> +++++ +++++ ++++.    Output 'dot'  Pointer 4 = 46");
        jScrollPane3.setViewportView(inputArea);

        jTabbedPane1.addTab("Source Code Editor", jScrollPane3);

        outputArea.setColumns(20);
        outputArea.setEditable(false);
        outputArea.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        outputArea.setRows(5);
        jScrollPane2.setViewportView(outputArea);

        jTabbedPane1.addTab("Program Output", jScrollPane2);

        debugArea.setColumns(20);
        debugArea.setEditable(false);
        debugArea.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        debugArea.setRows(5);
        jScrollPane5.setViewportView(debugArea);

        jTabbedPane1.addTab("Debug Information", jScrollPane5);

        infoPane.setBorder(null);
        infoPane.setEditable(false);
        infoPane.setFont(new java.awt.Font("Lucida Console", 2, 14)); // NOI18N
        infoPane.setForeground(new java.awt.Color(23, 23, 23));
        infoPane.setText("Welcome to the JavaFuck. This program allows you to run Brainfuck source code, either by entering a filepath to the source file, or by entering the source code into the text area on the right. Just enter the path to a local brainfuck source file, or type the source code into the editor, and click run. Future versions will inclued support for opening source files for editing, and saving edited source files. WARNING: Input and nested loops will not work right now. Do not try to use them, or your program will not run correctly.");
        jScrollPane4.setViewportView(infoPane);

        jLabel1.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        jLabel1.setText("Use source tab, or type a file-name:");

        filePathTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePathTextBoxActionPerformed(evt);
            }
        });

        filePathButton.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        filePathButton.setText("File path:");
        filePathButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                filePathButtonStateChanged(evt);
            }
        });
        filePathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePathButtonActionPerformed(evt);
            }
        });

        sourceTabButton.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        sourceTabButton.setSelected(true);
        sourceTabButton.setText("Source tab");
        sourceTabButton.setToolTipText("");
        sourceTabButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sourceTabButtonStateChanged(evt);
            }
        });
        sourceTabButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceTabButtonActionPerformed(evt);
            }
        });

        startButton.setText("Run code!");
        startButton.setToolTipText("Run the code from the source tab if the \"Source tab\" bubble is selected, or the from the specified file if the \"File path\" bubble is selected");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        clearSourceButton.setText("Clear Source");
        clearSourceButton.setToolTipText("Clears all text from the source tab");
        clearSourceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSourceButtonActionPerformed(evt);
            }
        });

        clearOutputButton.setText("Clear Output");
        clearOutputButton.setToolTipText("Clears all text from the output tab");
        clearOutputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearOutputButtonActionPerformed(evt);
            }
        });

        clearDebugButton.setText("Clear Dubug");
        clearDebugButton.setToolTipText("Clears all text from the debug tab");
        clearDebugButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearDebugButtonActionPerformed(evt);
            }
        });

        clearAllButton.setText("Clear All Tabs");
        clearAllButton.setToolTipText("Clears all text in the source, ooutput, and debug tabs");
        clearAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllButtonActionPerformed(evt);
            }
        });

        fileMenu.setText("File");

        menuOpen.setText("Open...");
        menuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpenActionPerformed(evt);
            }
        });
        fileMenu.add(menuOpen);

        menuSave.setText("Save...");
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        fileMenu.add(menuSave);

        menuSaveAs.setText("Save As...");
        menuSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveAsActionPerformed(evt);
            }
        });
        fileMenu.add(menuSaveAs);
        fileMenu.add(jSeparator1);

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        fileMenu.add(menuExit);

        jMenuBar1.add(fileMenu);

        editMenu.setText("Edit");

        menuCut.setText("Cut");
        menuCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCutActionPerformed(evt);
            }
        });
        editMenu.add(menuCut);

        menuCopy.setText("Copy");
        menuCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCopyActionPerformed(evt);
            }
        });
        editMenu.add(menuCopy);

        menuPaste.setText("Paste");
        menuPaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPasteActionPerformed(evt);
            }
        });
        editMenu.add(menuPaste);

        jMenuBar1.add(editMenu);

        helpMenu.setText("Help");

        menuAbout.setText("About");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        helpMenu.add(menuAbout);

        menuSampleProgram.setText("Sample Program");
        menuSampleProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSampleProgramActionPerformed(evt);
            }
        });
        helpMenu.add(menuSampleProgram);
        helpMenu.add(jSeparator2);

        menuHelp.setText("Help");
        menuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelpActionPerformed(evt);
            }
        });
        helpMenu.add(menuHelp);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(clearDebugButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearOutputButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sourceTabButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(filePathButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filePathTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(startButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearSourceButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filePathButton)
                            .addComponent(filePathTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sourceTabButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearSourceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearOutputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearDebugButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>
    
    public void setOutput(String s){
    	outputArea.setText(s);
    }
    
    public void setDebug(String s){
    	debugArea.setText(s);
    }
    
    public void setInput(String s){
    	inputArea.setText(s);
    }

    
    private void filePathTextBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void filePathButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void filePathButtonStateChanged(javax.swing.event.ChangeEvent evt) {
        if(filePathButton.isSelected()){
        	sourceTabButton.setSelected(false);
        }else{
        	sourceTabButton.setSelected(true);
        }
    }

    private void sourceTabButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void sourceTabButtonStateChanged(javax.swing.event.ChangeEvent evt) {
    	if(sourceTabButton.isSelected()){
    		filePathButton.setSelected(false);
        }else{
        	filePathButton.setSelected(true);
        }
    }

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	if(filePathButton.isSelected()){
    		bfi.runCodeFromFile(filePathTextBox.getText());
    	}else{
    		bfi.runCodeFromSource(inputArea.getText());
    	}
    	jTabbedPane1.setSelectedIndex(1);
    }

    private void clearSourceButtonActionPerformed(java.awt.event.ActionEvent evt) {
        inputArea.setText("");
    }

    private void clearOutputButtonActionPerformed(java.awt.event.ActionEvent evt) {
        outputArea.setText("");
    }

    private void clearDebugButtonActionPerformed(java.awt.event.ActionEvent evt) {
        debugArea.setText("");
    }

    private void clearAllButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	inputArea.setText("");
    	outputArea.setText("");
    	debugArea.setText("");
    }
    
    private void aboutOkayButtonActionPerformed(java.awt.event.ActionEvent evt){
    	aboutDialogBox.setVisible(false);
    }
    
    private void errorOkayButtonActionPerformed(java.awt.event.ActionEvent evt){
    	errorDialogBox.setVisible(false);
    }

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void menuSaveAsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void menuCutActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void menuCopyActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void menuPasteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {
    	aboutDialogBox.setSize(400, 300);
    	aboutDialogBox.setVisible(true);
    }

    private void menuHelpActionPerformed(java.awt.event.ActionEvent evt) {
    	helpDialogBox.setSize(600, 500);
        helpDialogBox.setVisible(true);
    }

    private void menuOpenActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    
    private void menuSampleProgramActionPerformed(java.awt.event.ActionEvent evt) {
        inputArea.setText("This is a sample hello world program\n\n+++++ +++++        Set pointer 0 to 10\n[\n > +++++ ++        Set pointer 1 to 70\n > +++++ +++++     Set pointer 2 to 100\n > +++++ +++++ ++  Set pointer 3 to 120\n > +++             Set pointer 4 to 30\n\n <<<< -            Decrement pointer 0\n]\n\n> ++.                   Output 'H'  Pointer 1 = 72\n> +.                    Output 'e'  Pointer 2 = 101\n+++++ ++.               Output 'l'  Pointer 2 = 108\n.                       Output 'l'  Pointer 2 = 108\n+++.                    Output 'o'  Pointer 2 = 111\n>> ++.                  Output ' '  Pointer 4 = 32\n<<< +++ +++++ +++++ ++. Output 'W'  Pointer 1 = 87\n>.                      Output 'o'  Pointer 2 = 111\n+++.                    Output 'r'  Pointer 2 = 114\n----- -.                Output 'l'  Pointer 2 = 108\n----- ---.              Output 'd'  Pointer 2 = 100\n>> +++++ +++++ ++++.    Output 'dot'  Pointer 4 = 46");
        jTabbedPane1.setSelectedIndex(0);
        outputArea.setText("");
        debugArea.setText("");
    }
   
    // Variables declaration - do not modify
    private javax.swing.JDialog aboutDialogBox;
    private javax.swing.JButton aboutOkayButton;
    private javax.swing.JButton clearAllButton;
    private javax.swing.JButton clearDebugButton;
    private javax.swing.JButton clearOutputButton;
    private javax.swing.JButton clearSourceButton;
    private javax.swing.JTextArea debugArea;
    private javax.swing.JMenu editMenu;
    private javax.swing.JDialog errorDialogBox;
    private javax.swing.JButton errorOkayButton;
    private javax.swing.JLabel errorText;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JRadioButton filePathButton;
    private javax.swing.JTextField filePathTextBox;
    private javax.swing.JDialog helpDialogBox;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JTextPane infoPane;
    private javax.swing.JTextArea inputArea;
    private javax.swing.JOptionPane inputPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuCopy;
    private javax.swing.JMenuItem menuCut;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuHelp;
    private javax.swing.JMenuItem menuOpen;
    private javax.swing.JMenuItem menuPaste;
    private javax.swing.JMenuItem menuSampleProgram;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JMenuItem menuSaveAs;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JRadioButton sourceTabButton;
    private javax.swing.JButton startButton;
    // End of variables declaration
}
